// This file is auto-generated by @hey-api/openapi-ts

import * as sdk from './sdk.gen';

declare module '@sitecore-marketplace-sdk/client' {
  interface QueryMap {}
}

declare module '@sitecore-marketplace-sdk/client' {
  interface MutationMap {
    /**
     * Send a GraphQL query or mutation request to the Sitecore Authoring API. Both queries and mutations are supported.*/
    'xmc.authoring.authoringGraphql': {
      params: Parameters<typeof sdk.authoringGraphql>[0];
      response: Awaited<ReturnType<typeof sdk.authoringGraphql>>;
    };
  }
}
