// This file is auto-generated by @hey-api/openapi-ts

import * as sdk from './sdk.gen';

declare module '@sitecore-marketplace-sdk/client' {
  interface QueryMap {}
}

declare module '@sitecore-marketplace-sdk/client' {
  interface MutationMap {
    'xmc.authoring.graphql': {
      params: Parameters<typeof sdk.graphql>[0];
      response: Awaited<ReturnType<typeof sdk.graphql>>;
    };
  }
}
