// This file is auto-generated by @hey-api/openapi-ts

import * as sdk from './sdk.gen';

declare module '@sitecore-marketplace-sdk/client' {
  interface QueryMap {
    'xmc.xmapp.listLanguages': {
      params: Parameters<typeof sdk.listLanguages>[0];
      response: Awaited<ReturnType<typeof sdk.listLanguages>>;
      subscribe: false;
    };
    'xmc.xmapp.listSupportedLanguages': {
      params: Parameters<typeof sdk.listSupportedLanguages>[0];
      response: Awaited<ReturnType<typeof sdk.listSupportedLanguages>>;
      subscribe: false;
    };
    'xmc.xmapp.listPageVariants': {
      params: Parameters<typeof sdk.listPageVariants>[0];
      response: Awaited<ReturnType<typeof sdk.listPageVariants>>;
      subscribe: false;
    };
    'xmc.xmapp.getLivePageState': {
      params: Parameters<typeof sdk.getLivePageState>[0];
      response: Awaited<ReturnType<typeof sdk.getLivePageState>>;
      subscribe: false;
    };
    'xmc.xmapp.listCollections': {
      params: Parameters<typeof sdk.listCollections>[0];
      response: Awaited<ReturnType<typeof sdk.listCollections>>;
      subscribe: false;
    };
    'xmc.xmapp.retrieveCollection': {
      params: Parameters<typeof sdk.retrieveCollection>[0];
      response: Awaited<ReturnType<typeof sdk.retrieveCollection>>;
      subscribe: false;
    };
    'xmc.xmapp.getFavoriteSites': {
      params: Parameters<typeof sdk.getFavoriteSites>[0];
      response: Awaited<ReturnType<typeof sdk.getFavoriteSites>>;
      subscribe: false;
    };
    'xmc.xmapp.listJobs': {
      params: Parameters<typeof sdk.listJobs>[0];
      response: Awaited<ReturnType<typeof sdk.listJobs>>;
      subscribe: false;
    };
    'xmc.xmapp.retrieveJob': {
      params: Parameters<typeof sdk.retrieveJob>[0];
      response: Awaited<ReturnType<typeof sdk.retrieveJob>>;
      subscribe: false;
    };
    'xmc.xmapp.listSites': {
      params: Parameters<typeof sdk.listSites>[0];
      response: Awaited<ReturnType<typeof sdk.listSites>>;
      subscribe: false;
    };
    'xmc.xmapp.retrieveSite': {
      params: Parameters<typeof sdk.retrieveSite>[0];
      response: Awaited<ReturnType<typeof sdk.retrieveSite>>;
      subscribe: false;
    };
    'xmc.xmapp.listTrackedSites': {
      params: Parameters<typeof sdk.listTrackedSites>[0];
      response: Awaited<ReturnType<typeof sdk.listTrackedSites>>;
      subscribe: false;
    };
    'xmc.xmapp.listCollectionSites': {
      params: Parameters<typeof sdk.listCollectionSites>[0];
      response: Awaited<ReturnType<typeof sdk.listCollectionSites>>;
      subscribe: false;
    };
    'xmc.xmapp.retrieveSiteHierarchy': {
      params: Parameters<typeof sdk.retrieveSiteHierarchy>[0];
      response: Awaited<ReturnType<typeof sdk.retrieveSiteHierarchy>>;
      subscribe: false;
    };
    'xmc.xmapp.retrievePageHierarchy': {
      params: Parameters<typeof sdk.retrievePageHierarchy>[0];
      response: Awaited<ReturnType<typeof sdk.retrievePageHierarchy>>;
      subscribe: false;
    };
    'xmc.xmapp.listPageAncestors': {
      params: Parameters<typeof sdk.listPageAncestors>[0];
      response: Awaited<ReturnType<typeof sdk.listPageAncestors>>;
      subscribe: false;
    };
    'xmc.xmapp.listPageChildren': {
      params: Parameters<typeof sdk.listPageChildren>[0];
      response: Awaited<ReturnType<typeof sdk.listPageChildren>>;
      subscribe: false;
    };
    'xmc.xmapp.listHosts': {
      params: Parameters<typeof sdk.listHosts>[0];
      response: Awaited<ReturnType<typeof sdk.listHosts>>;
      subscribe: false;
    };
    'xmc.xmapp.retrieveHost': {
      params: Parameters<typeof sdk.retrieveHost>[0];
      response: Awaited<ReturnType<typeof sdk.retrieveHost>>;
      subscribe: false;
    };
    'xmc.xmapp.getRenderingHosts': {
      params: Parameters<typeof sdk.getRenderingHosts>[0];
      response: Awaited<ReturnType<typeof sdk.getRenderingHosts>>;
      subscribe: false;
    };
    'xmc.xmapp.listSiteTemplates': {
      params: Parameters<typeof sdk.listSiteTemplates>[0];
      response: Awaited<ReturnType<typeof sdk.listSiteTemplates>>;
      subscribe: false;
    };
    'xmc.xmapp.retrieveLocalizationStatistics': {
      params: Parameters<typeof sdk.retrieveLocalizationStatistics>[0];
      response: Awaited<ReturnType<typeof sdk.retrieveLocalizationStatistics>>;
      subscribe: false;
    };
    'xmc.xmapp.retrieveSitemapConfiguration': {
      params: Parameters<typeof sdk.retrieveSitemapConfiguration>[0];
      response: Awaited<ReturnType<typeof sdk.retrieveSitemapConfiguration>>;
      subscribe: false;
    };
    'xmc.xmapp.retrieveWorkflowStatistics': {
      params: Parameters<typeof sdk.retrieveWorkflowStatistics>[0];
      response: Awaited<ReturnType<typeof sdk.retrieveWorkflowStatistics>>;
      subscribe: false;
    };
  }
}

declare module '@sitecore-marketplace-sdk/client' {
  interface MutationMap {
    'xmc.xmapp.createLanguage': {
      params: Parameters<typeof sdk.createLanguage>[0];
      response: Awaited<ReturnType<typeof sdk.createLanguage>>;
    };
    'xmc.xmapp.createCollection': {
      params: Parameters<typeof sdk.createCollection>[0];
      response: Awaited<ReturnType<typeof sdk.createCollection>>;
    };
    'xmc.xmapp.deleteCollection': {
      params: Parameters<typeof sdk.deleteCollection>[0];
      response: Awaited<ReturnType<typeof sdk.deleteCollection>>;
    };
    'xmc.xmapp.updateCollection': {
      params: Parameters<typeof sdk.updateCollection>[0];
      response: Awaited<ReturnType<typeof sdk.updateCollection>>;
    };
    'xmc.xmapp.addFavoriteSite': {
      params: Parameters<typeof sdk.addFavoriteSite>[0];
      response: Awaited<ReturnType<typeof sdk.addFavoriteSite>>;
    };
    'xmc.xmapp.aggregateLivePageVariants': {
      params: Parameters<typeof sdk.aggregateLivePageVariants>[0];
      response: Awaited<ReturnType<typeof sdk.aggregateLivePageVariants>>;
    };
    'xmc.xmapp.aggregatePageData': {
      params: Parameters<typeof sdk.aggregatePageData>[0];
      response: Awaited<ReturnType<typeof sdk.aggregatePageData>>;
    };
    'xmc.xmapp.renameCollection': {
      params: Parameters<typeof sdk.renameCollection>[0];
      response: Awaited<ReturnType<typeof sdk.renameCollection>>;
    };
    'xmc.xmapp.sortCollections': {
      params: Parameters<typeof sdk.sortCollections>[0];
      response: Awaited<ReturnType<typeof sdk.sortCollections>>;
    };
    'xmc.xmapp.validateCollectionName': {
      params: Parameters<typeof sdk.validateCollectionName>[0];
      response: Awaited<ReturnType<typeof sdk.validateCollectionName>>;
    };
    'xmc.xmapp.deleteLanguage': {
      params: Parameters<typeof sdk.deleteLanguage>[0];
      response: Awaited<ReturnType<typeof sdk.deleteLanguage>>;
    };
    'xmc.xmapp.updateLanguage': {
      params: Parameters<typeof sdk.updateLanguage>[0];
      response: Awaited<ReturnType<typeof sdk.updateLanguage>>;
    };
    'xmc.xmapp.removeFavoriteSite': {
      params: Parameters<typeof sdk.removeFavoriteSite>[0];
      response: Awaited<ReturnType<typeof sdk.removeFavoriteSite>>;
    };
    'xmc.xmapp.createSite': {
      params: Parameters<typeof sdk.createSite>[0];
      response: Awaited<ReturnType<typeof sdk.createSite>>;
    };
    'xmc.xmapp.deleteSite': {
      params: Parameters<typeof sdk.deleteSite>[0];
      response: Awaited<ReturnType<typeof sdk.deleteSite>>;
    };
    'xmc.xmapp.updateSite': {
      params: Parameters<typeof sdk.updateSite>[0];
      response: Awaited<ReturnType<typeof sdk.updateSite>>;
    };
    'xmc.xmapp.copySite': {
      params: Parameters<typeof sdk.copySite>[0];
      response: Awaited<ReturnType<typeof sdk.copySite>>;
    };
    'xmc.xmapp.renameSite': {
      params: Parameters<typeof sdk.renameSite>[0];
      response: Awaited<ReturnType<typeof sdk.renameSite>>;
    };
    'xmc.xmapp.sortSites': {
      params: Parameters<typeof sdk.sortSites>[0];
      response: Awaited<ReturnType<typeof sdk.sortSites>>;
    };
    'xmc.xmapp.validateSiteName': {
      params: Parameters<typeof sdk.validateSiteName>[0];
      response: Awaited<ReturnType<typeof sdk.validateSiteName>>;
    };
    'xmc.xmapp.detachAnalyticsIdentifier': {
      params: Parameters<typeof sdk.detachAnalyticsIdentifier>[0];
      response: Awaited<ReturnType<typeof sdk.detachAnalyticsIdentifier>>;
    };
    'xmc.xmapp.createHost': {
      params: Parameters<typeof sdk.createHost>[0];
      response: Awaited<ReturnType<typeof sdk.createHost>>;
    };
    'xmc.xmapp.deleteHost': {
      params: Parameters<typeof sdk.deleteHost>[0];
      response: Awaited<ReturnType<typeof sdk.deleteHost>>;
    };
    'xmc.xmapp.updateHost': {
      params: Parameters<typeof sdk.updateHost>[0];
      response: Awaited<ReturnType<typeof sdk.updateHost>>;
    };
    'xmc.xmapp.uploadSiteThumbnail': {
      params: Parameters<typeof sdk.uploadSiteThumbnail>[0];
      response: Awaited<ReturnType<typeof sdk.uploadSiteThumbnail>>;
    };
    'xmc.xmapp.updateSitemapConfiguration': {
      params: Parameters<typeof sdk.updateSitemapConfiguration>[0];
      response: Awaited<ReturnType<typeof sdk.updateSitemapConfiguration>>;
    };
  }
}
