// This file is auto-generated by @hey-api/openapi-ts

import * as sdk from './sdk.gen';

declare module '@sitecore-marketplace-sdk/client' {
  interface QueryMap {
    'xmc.contentTransfer.getContentTransferStatus': {
      params: Parameters<typeof sdk.getContentTransferStatus>[0];
      response: Awaited<ReturnType<typeof sdk.getContentTransferStatus>>;
      subscribe: false;
    };
    'xmc.contentTransfer.getChunk': {
      params: Parameters<typeof sdk.getChunk>[0];
      response: Awaited<ReturnType<typeof sdk.getChunk>>;
      subscribe: false;
    };
    'xmc.contentTransfer.consumeFile': {
      params: Parameters<typeof sdk.consumeFile>[0];
      response: Awaited<ReturnType<typeof sdk.consumeFile>>;
      subscribe: false;
    };
    'xmc.contentTransfer.getBlobState': {
      params: Parameters<typeof sdk.getBlobState>[0];
      response: Awaited<ReturnType<typeof sdk.getBlobState>>;
      subscribe: false;
    };
  }
}

declare module '@sitecore-marketplace-sdk/client' {
  interface MutationMap {
    'xmc.contentTransfer.createContentTransfer': {
      params: Parameters<typeof sdk.createContentTransfer>[0];
      response: Awaited<ReturnType<typeof sdk.createContentTransfer>>;
    };
    'xmc.contentTransfer.saveChunk': {
      params: Parameters<typeof sdk.saveChunk>[0];
      response: Awaited<ReturnType<typeof sdk.saveChunk>>;
    };
    'xmc.contentTransfer.completeChunkSetTransfer': {
      params: Parameters<typeof sdk.completeChunkSetTransfer>[0];
      response: Awaited<ReturnType<typeof sdk.completeChunkSetTransfer>>;
    };
    'xmc.contentTransfer.deleteContentTransfer': {
      params: Parameters<typeof sdk.deleteContentTransfer>[0];
      response: Awaited<ReturnType<typeof sdk.deleteContentTransfer>>;
    };
  }
}
